/**
 * UI strings — used for hardcoded text that's not in the main i18n dict.
 * Keeps it simple: one function, returns { [key]: string } for the given language.
 */

import type { Lang } from './i18n';

type UIStrings = Record<string, string>;

const STRINGS: Record<Lang, UIStrings> = {
  en: {
    popular: 'Popular',
    random: 'Random',
    ranks: 'Ranks',
    awards: 'Awards',
    profile: 'Profile',
    home: 'Home',
    daily_challenge: 'Daily Challenge',
    quiz_of_week: 'Quiz of the Week',
    category_stats: 'Category Stats',
    unlocked: 'Unlocked',
    locked: 'Locked',
    all_time: 'All time',
    this_week: 'This week',
    browse_quizzes: 'Browse quizzes',
    play_classic: 'Play Classic',
    play_attack: 'Play Time Attack',
    play_survival: 'Play Survival',
    select_mode: 'Select mode',
    classic: 'Classic',
    time_attack: 'Time Attack',
    survival: 'Survival',
    classic_desc: '10 questions, 15s each',
    attack_desc: '60s, max correct',
    survival_desc: '1 wrong = game over',
    correct: 'Correct!',
    wrong: 'Wrong!',
    times_up: "Time's up!",
    correct_answer_is: 'The correct answer is highlighted.',
    hints_left: 'left',
    no_hints: 'No hints left',
    get_pro: 'Get Pro',
    next_rank: 'Next',
    at_level: 'at Lv',
    exit: 'Exit',
    loading: 'Loading...',
    questions: 'questions',
    answered: 'answered',
    level: 'Level',
    played: 'Played',
    streak: 'Streak',
    xp: 'XP',
    days: 'days',
    or_tap: 'or tap',
    play_weekly: 'Play weekly',
    view_all: 'All',
  },
  ru: {
    popular: 'Популярные',
    random: 'Случайный',
    ranks: 'Рейтинг',
    awards: 'Награды',
    profile: 'Профиль',
    home: 'Главная',
    daily_challenge: 'Челлендж дня',
    quiz_of_week: 'Квиз недели',
    category_stats: 'Статистика',
    unlocked: 'Открыто',
    locked: 'Закрыто',
    all_time: 'За всё время',
    this_week: 'На этой неделе',
    browse_quizzes: 'Все квизы',
    play_classic: 'Играть Классик',
    play_attack: 'Играть Атака',
    play_survival: 'Играть Выживание',
    select_mode: 'Выбери режим',
    classic: 'Классик',
    time_attack: 'Атака',
    survival: 'Выживание',
    classic_desc: '10 вопросов, 15с каждый',
    attack_desc: '60с, максимум правильных',
    survival_desc: '1 ошибка = конец',
    correct: 'Верно!',
    wrong: 'Неверно!',
    times_up: 'Время вышло!',
    correct_answer_is: 'Правильный ответ подсвечен.',
    hints_left: 'осталось',
    no_hints: 'Подсказки кончились',
    get_pro: 'Купить Pro',
    next_rank: 'Следующий',
    at_level: 'на Ур',
    exit: 'Выход',
    loading: 'Загрузка...',
    questions: 'вопросов',
    answered: 'отвечено',
    level: 'Уровень',
    played: 'Сыграно',
    streak: 'Серия',
    xp: 'XP',
    days: 'дней',
    or_tap: 'или тап',
    play_weekly: 'Играть',
    view_all: 'Все',
  },
  es: {
    popular: 'Populares', random: 'Aleatorio', ranks: 'Ranking', awards: 'Logros', profile: 'Perfil', home: 'Inicio',
    daily_challenge: 'Reto diario', quiz_of_week: 'Quiz de la semana', category_stats: 'Estadísticas',
    unlocked: 'Desbloqueado', locked: 'Bloqueado', all_time: 'Todo el tiempo', this_week: 'Esta semana',
    browse_quizzes: 'Ver quizzes', play_classic: 'Jugar Clásico', play_attack: 'Jugar Ataque', play_survival: 'Jugar Supervivencia',
    select_mode: 'Selecciona modo', classic: 'Clásico', time_attack: 'Ataque', survival: 'Supervivencia',
    classic_desc: '10 preguntas, 15s cada una', attack_desc: '60s, máximo correctas', survival_desc: '1 error = fin',
    correct: '¡Correcto!', wrong: '¡Incorrecto!', times_up: '¡Tiempo!', correct_answer_is: 'La respuesta correcta está resaltada.',
    hints_left: 'restantes', no_hints: 'Sin pistas', get_pro: 'Obtener Pro', next_rank: 'Siguiente', at_level: 'en Nv',
    exit: 'Salir', loading: 'Cargando...', questions: 'preguntas', answered: 'respondidas', level: 'Nivel', played: 'Jugados', streak: 'Racha', xp: 'XP', days: 'días', or_tap: 'o toca', play_weekly: 'Jugar', view_all: 'Todos',
  },
  de: {
    popular: 'Beliebt', random: 'Zufällig', ranks: 'Rangliste', awards: 'Erfolge', profile: 'Profil', home: 'Start',
    daily_challenge: 'Tägliche Herausforderung', quiz_of_week: 'Quiz der Woche', category_stats: 'Statistiken',
    unlocked: 'Freigeschaltet', locked: 'Gesperrt', all_time: 'Gesamt', this_week: 'Diese Woche',
    browse_quizzes: 'Quizzes ansehen', play_classic: 'Klassisch', play_attack: 'Zeitangriff', play_survival: 'Überleben',
    select_mode: 'Modus wählen', classic: 'Klassisch', time_attack: 'Angriff', survival: 'Überleben',
    classic_desc: '10 Fragen, 15s jede', attack_desc: '60s, max richtig', survival_desc: '1 falsch = Ende',
    correct: 'Richtig!', wrong: 'Falsch!', times_up: 'Zeit!', correct_answer_is: 'Die richtige Antwort ist markiert.',
    hints_left: 'übrig', no_hints: 'Keine Tipps', get_pro: 'Pro holen', next_rank: 'Nächster', at_level: 'bei Lv',
    exit: 'Exit', loading: 'Lädt...', questions: 'Fragen', answered: 'beantwortet', level: 'Level', played: 'Gespielt', streak: 'Serie', xp: 'XP', days: 'Tage', or_tap: 'oder tippen', play_weekly: 'Spielen', view_all: 'Alle',
  },
  fr: {
    popular: 'Populaires', random: 'Aléatoire', ranks: 'Classement', awards: 'Trophées', profile: 'Profil', home: 'Accueil',
    daily_challenge: 'Défi quotidien', quiz_of_week: 'Quiz de la semaine', category_stats: 'Statistiques',
    unlocked: 'Débloqué', locked: 'Verrouillé', all_time: 'Tout temps', this_week: 'Cette semaine',
    browse_quizzes: 'Voir quizzes', play_classic: 'Jouer Classique', play_attack: 'Jouer Attaque', play_survival: 'Jouer Survie',
    select_mode: 'Choisir mode', classic: 'Classique', time_attack: 'Attaque', survival: 'Survie',
    classic_desc: '10 questions, 15s chacune', attack_desc: '60s, max correctes', survival_desc: '1 erreur = fin',
    correct: 'Correct !', wrong: 'Faux !', times_up: 'Temps écoulé !', correct_answer_is: 'La bonne réponse est surlignée.',
    hints_left: 'restantes', no_hints: 'Plus d\'indices', get_pro: 'Obtenir Pro', next_rank: 'Suivant', at_level: 'au Nv',
    exit: 'Quitter', loading: 'Chargement...', questions: 'questions', answered: 'répondues', level: 'Niveau', played: 'Joués', streak: 'Série', xp: 'XP', days: 'jours', or_tap: 'ou tapez', play_weekly: 'Jouer', view_all: 'Tous',
  },
};

export function ui(lang: Lang, key: string): string {
  return STRINGS[lang]?.[key] ?? STRINGS.en[key] ?? key;
}
